num = int (input("Digite um número para ver uma tabuada: "))
print ("-------------------")
print (f"{num} x {1:2} = {num * 1:3}")
print (f"{num} x {2:2} = {num * 2:3}")
print (f"{num} x {3:2} = {num * 3:3}")
print (f"{num} x {4:2} = {num * 4:3}")
print (f"{num} x {5:2} = {num * 5:3}")
print (f"{num} x {6:2} = {num * 6:3}")
print (f"{num} x {7:2} = {num * 7:3}")
print (f"{num} x {8:2} = {num * 8:3}")
print (f"{num} x {9:2} = {num * 9:3}")
print (f"{num} x {10:2} = {num * 10:3}")
print ("-------------------")